# Generated by Django 4.2 on 2023-04-27 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaModels',
            fields=[
                ('cate_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('cate_nome', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutosModels',
            fields=[
                ('prod_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('prod_nome', models.CharField(max_length=80)),
                ('prod_estoque', models.IntegerField(max_length=200)),
                ('prod_preco', models.FloatField(max_length=20)),
                ('prod_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.categoriamodels')),
            ],
        ),
    ]
