# Generated by Django 4.2 on 2023-04-28 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtosmodels',
            name='prod_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.categoriamodels', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='produtosmodels',
            name='prod_estoque',
            field=models.IntegerField(max_length=200, verbose_name='Estoque'),
        ),
        migrations.AlterField(
            model_name='produtosmodels',
            name='prod_nome',
            field=models.CharField(max_length=80, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='produtosmodels',
            name='prod_preco',
            field=models.FloatField(max_length=20, verbose_name='Preço'),
        ),
        migrations.CreateModel(
            name='CompraModels',
            fields=[
                ('comp_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('comp_quantidade', models.IntegerField(max_length=200)),
                ('comp_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produtosmodels')),
                ('comp_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
