# Generated by Django 4.2 on 2023-04-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produtosmodels_prod_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compramodels',
            name='comp_quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
